baseDir: c:\win10
#使用${属性名}引用数据
tempDir: ${baseDir}\temp
#使用引号包裹的字符串，其中的转义字符可以生效
tempDir2: "${baseDir}\temp \t1 \t2 \t3"

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: 123456

enterprise:
  name: itcast
  age: 16
  tel: 778788998
  subject:
    - java
    - CC#
    - C++